### ISSUE TITLE
The meaning of padlen and pad char

### ISSUE THREAD

**Issue by Neroldy** [lennylxx/IG_tools#1]
In the igscript.cpp
```
				if (padlen >= 1) {
					for (u8 i = 0; i<padlen; i++) {
						outfile << buf[i + txt.length()];
					}
				}
```
It seems that we don't know the pad char's meaning ? But in my case, these pad char will result some output in the game, such as "乧"
Any solutions ? Thanks~

**Comment by lennylxx** [comment]
I wrote this code a long time ago.
I believe that the pad is for "padding", it's not just padding with empty character, but also some special character I don't know what's it, so I take them from the tail the original string and append it to the new string.

**Comment by Neroldy** [comment]
Thanks for reply.
====================
菊苣你是国人吧，由于我的渣英语，还是用中文表达会贴切一点吧。
就是如果按照代码中将这些padding字符放到末尾的话，汉化版经常会在句子的末尾出现那些由padding字符导致的乱码。如果把它们都置成了00，就没有了，且好像现在也没有什么问题。载到OD看了看，发现每句话在输出的时候，末尾的padding字符也会一并复制到后面，虽然padding字符的第一个byte总是00，但是后面的乱码仍然会输出。暂时还没有猜到这些padding字符的含义是啥。感觉有点像是干扰字符。

**Comment by lennylxx** [comment]
我当时好像也是没有搞清楚这些字符的作用，但是害怕影响游戏运行，就原样复制过来了。
如果现在导致了乱码，直接把这几行注释掉就好了。

**Comment by Neroldy** [comment]
ok。多谢。
P.S.
debug的过程中发现了一个代码中没有覆盖的case
```
			case 0x083B://jump
			case 0x080D://jump
				break;
```
这个0x083B是个二周目出现的选择支，处理上和0x080D一致，否则原来的代码生成的脚本在二周目的时候会报错。

**Comment by lennylxx** [comment]
欢迎发起Pull Request :P
