### ISSUE TITLE
igscript.exe missing

### ISSUE THREAD

**Issue by dashaund** [lennylxx/IG_tools#3]
Hello, I am very interested in using this to edit some scripts from FLOWERS but the igscript.exe is missing. Did you remove it? Would it be a problem if you could upload it again?

Thank you.

**Comment by lennylxx** [comment]
Sorry, this is only source code repository, you need to compile the executable file yourself.

**Comment by dashaund** [comment]
Thanks!

**Comment by Lynn882** [comment]
Hello, I use this to get scripts of FLOWERS, but words in txt is just some thing no meaning. I don't know if I do the step "compile the executable file" wrong or nowadays *.s file can't use this anymore. My English is poor. So, I don't know if I express my meaning clearly. Could you please help me? Thank you very much.

**Comment by lennylxx** [comment]
@Lynn882 Please upload your *.s files in the comment. I will have a look.
