### ISSUE TITLE
Tools not working

### ISSUE THREAD

**Issue by knatum97** [lennylxx/IG_tools#4]
I've been trying to translate Caucasus and compiled igtool/script.exe and tried to execute them, but they do not seem to work:  both igtool and igscript shuts down immediately when I click them.
I have made sure that the necessary dll's are installed, and igtool is in the same directory as script.dat.
I may be doing something wrong, but do not know what the problem is. Please help me if you can.
ps. I am using windows 10, japanese locale.(have tested on english locale as well, still not working)

**Comment by lennylxx** [comment]
Hi, these are command line applications, you can't run them by just using mouse to click on them.
Please press Win+R and type "cmd" and hit "Enter" key to open a cmd.exe.
Then use "cd" command to change to the folder which contains the exe files.
And then type "igtool -x script.dat" to use it.

**Comment by knatum97** [comment]
It works!!!!!! I didn't know about the cd part and was entering the commands to sys32.. 
now both extraction and script converting works perfectly! Thank you so much!!!

**Comment by Neroldy** [comment]
@knatum97 Please verify the text carefully, maybe you will meet some "new" pattern that not add in the src. Direct decrtpt the *.s file and compare the text would be a good way. Just some my experience of processing FLOWERS.
