### ISSUE TITLE
question: any idea how to repack the script to iga?

### ISSUE THREAD

**Issue by 0xh3LL0** [lennylxx/IG_tools#5]
tried your tools, works very well...
but how we repack all of the edited script to a single iga file, since igtool only support .dat file?
afaik, exiga only support for extraction,
or we just need to put the edited script (*.s) to the game directory, and it will work?

**Comment by Neroldy** [comment]
@0xh3LL0 Here, use igatool
https://github.com/Inori/FuckGalEngine/tree/master/InnocentGrey/IGKit

**Comment by 0xh3LL0** [comment]
thanks for the info, i'll try it.
